# Generated by Django 5.2.5 on 2025-08-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='predicted_disease',
            field=models.TextField(),
        ),
    ]
