# Generated by Django 5.2.5 on 2025-09-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='recommended_doctor',
            field=models.CharField(default='General Physician', max_length=255),
        ),
    ]
